#! /bin/sh

sxhkd &
feh --bg-tile ~/.fluxbox/backgrounds/black.png &
xscreensaver -no-splash &
dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
